# Generated by Django 2.2.10 on 2020-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="truck",
            options={"verbose_name": "Truck", "verbose_name_plural": "Trucks"},
        ),
        migrations.AlterField(
            model_name="truck",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Truck"),
        ),
    ]
