# Generated by Django 2.2b1 on 2019-03-25 16:24

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_type',
            field=models.CharField(choices=[('Einzelunternehmen', 'Einzelunternehmen'), ('Landwirtschaftliche GbR', 'Landwirtschaftliche GbR'), ('Gewerbliche GbR', 'Gewerbliche GbR'), ('eG', 'eG'), ('KG', 'KG'), ('AG', 'AG'), ('GmbH', 'GmbH'), ('GmbH & Co. KG', 'GmbH & Co. KG'), ('UG (haftungsbeschränkt)', 'UG (haftungsbeschränkt)'), ('OHG', 'OHG'), ('e.V.', 'e.V.')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality_country_code',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='residence_country_code',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
