# Generated by Django 2.2rc1 on 2019-03-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190325_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mangopay_validation_level',
            field=models.CharField(blank=True, default='light', max_length=255, null=True),
        ),
    ]
