# Generated by Django 2.2rc1 on 2019-04-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190328_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iban',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
