# Generated by Django 2.2rc1 on 2019-04-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('users', '0004_auto_20190410_1211')]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invoice_email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        )
    ]
