# Generated by Django 2.2.1 on 2019-07-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tax_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
