# Generated by Django 2.2.1 on 2019-08-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190702_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_type',
            field=models.CharField(choices=[('Einzelunternehmer', 'Einzelunternehmer'), ('Landwirtschaftliche GbR', 'Landwirtschaftliche GbR'), ('Gewerbliche GbR', 'Gewerbliche GbR'), ('eG', 'eG'), ('KG', 'KG'), ('AG', 'AG'), ('GmbH', 'GmbH'), ('GmbH & Co. KG', 'GmbH & Co. KG'), ('UG (haftungsbeschränkt)', 'UG (haftungsbeschränkt)'), ('OHG', 'OHG'), ('e.V.', 'e.V.')], max_length=255),
        ),
    ]
