# Generated by Django 2.2.1 on 2019-11-12 16:47

import core.storage.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190827_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.utils.public_image_upload_to),
        ),
    ]
