# Generated by Django 2.2.1 on 2019-11-12 17:25

import core.storage.utils
from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_license',
            field=models.FileField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(GS_BUCKET_NAME='meck-schweizer-dev.appspot.com', GS_DEFAULT_ACL=None), upload_to=core.storage.utils.private_image_upload_to),
        ),
        migrations.AddField(
            model_name='user',
            name='drivers_license_photo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(GS_BUCKET_NAME='meck-schweizer-dev.appspot.com', GS_DEFAULT_ACL=None), upload_to=core.storage.utils.private_image_upload_to),
        ),
        migrations.AddField(
            model_name='user',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(GS_BUCKET_NAME='meck-schweizer-dev.appspot.com', GS_DEFAULT_ACL=None), upload_to=core.storage.utils.private_image_upload_to),
        ),
    ]
