# Generated by Django 2.2.4 on 2020-01-14 09:29

import core.storage.utils
from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191112_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cooperative_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_license',
            field=models.FileField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(default_acl='projectPrivate'), upload_to=core.storage.utils.private_image_upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='drivers_license_photo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(default_acl='projectPrivate'), upload_to=core.storage.utils.private_image_upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(default_acl='projectPrivate'), upload_to=core.storage.utils.private_image_upload_to),
        ),
    ]
