# Generated by Django 2.2.4 on 2020-04-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200406_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
