# Generated by Django 2.2.4 on 2020-04-17 09:38

from django.db import migrations, models


def replace_null_with_blank(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(invoice_email=None).update(invoice_email="")


class Migration(migrations.Migration):

    dependencies = [("users", "0014_auto_20200410_1013")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="invoice_email",
            field=models.EmailField(blank=True, null=True, max_length=255),
        ),
        migrations.RunPython(replace_null_with_blank, reverse_code=lambda: True),
        migrations.AlterField(
            model_name="user",
            name="invoice_email",
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
