# Generated by Django 2.2.4 on 2020-04-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("users", "0014_auto_20200410_1013")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="invoice_email",
            field=models.EmailField(blank=True, null=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="invoice_email",
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
