# Generated by Django 2.2.10 on 2020-05-07 07:33

import core.storage.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200417_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=core.storage.utils.private_image_upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_license',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=core.storage.utils.private_image_upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=core.storage.utils.private_image_upload_to),
        ),
    ]
