# Generated by Django 2.2.10 on 2020-05-20 13:23

import core.storage.utils
from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_auto_20200507_0733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycdocument",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to=core.storage.utils.private_image_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="business_license",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to=core.storage.utils.private_image_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to=core.storage.utils.private_image_upload_to,
            ),
        ),
    ]
