# Generated by Django 2.2.10 on 2020-05-20 15:39

import core.storage.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import storages.backends.gcloud
import users.models.kyc
from users.models.kyc import KycDocument


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_auto_20200520_1323"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kycdocument",
            options={
                "verbose_name": "KYC document",
                "verbose_name_plural": "KYC documents",
            },
        ),
        migrations.AlterField(
            model_name="kycdocument",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to=core.storage.utils.private_image_upload_to,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="kycdocument",
            name="name",
            field=models.CharField(
                choices=[
                    (KycDocument.Name("IDENTITY_PROOF"), "IDENTITY_PROOF"),
                    (
                        KycDocument.Name("ARTICLES_OF_ASSOCIATION"),
                        "ARTICLES_OF_ASSOCIATION",
                    ),
                    (KycDocument.Name("REGISTRATION_PROOF"), "REGISTRATION_PROOF"),
                    (KycDocument.Name("ADDRESS_PROOF"), "ADDRESS_PROOF"),
                    (
                        KycDocument.Name("SHAREHOLDER_DECLARATION"),
                        "SHAREHOLDER_DECLARATION",
                    ),
                ],
                max_length=30,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="kycdocument",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="association_registration_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Association registration id",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bank",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Bank name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bic",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="BIC account number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(verbose_name="Birth date"),
        ),
        migrations.AlterField(
            model_name="user",
            name="business_license",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to=core.storage.utils.private_image_upload_to,
                verbose_name="Business license",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="business_license_url",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Business license url",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=255, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="user",
            name="company_name",
            field=models.CharField(max_length=255, verbose_name="Company name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="company_registration_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Company registration id",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("Einzelunternehmer", "Einzelunternehmer"),
                    ("Landwirtschaftliche GbR", "Landwirtschaftliche GbR"),
                    ("Gewerbliche GbR", "Gewerbliche GbR"),
                    ("eG", "eG"),
                    ("KG", "KG"),
                    ("AG", "AG"),
                    ("GmbH", "GmbH"),
                    ("GmbH & Co. KG", "GmbH & Co. KG"),
                    ("UG (haftungsbeschränkt)", "UG (haftungsbeschränkt)"),
                    ("OHG", "OHG"),
                    ("e.V.", "e.V."),
                ],
                max_length=255,
                verbose_name="Company type",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="declared_as_seller",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Declared as seller"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="iban",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="IBAN number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to=core.storage.utils.private_image_upload_to,
                verbose_name="ID photo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_photo_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Id photo url"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.storage.utils.public_image_upload_to,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Image url"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="invoice_email",
            field=models.EmailField(
                blank=True, max_length=255, verbose_name="Invoice email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_certified_organic_producer",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Is certified organic producer",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_cooperative_member",
            field=models.BooleanField(
                default=False, verbose_name="Is cooperative member"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="Is email verified"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="mangopay_user_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Mangopay user id"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mangopay_user_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Mangopay user type"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mangopay_validation_level",
            field=models.CharField(
                blank=True,
                default="light",
                max_length=255,
                null=True,
                verbose_name="Mangopay validation level",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nationality_country_code",
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name="Nationality country code"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organic_control_body",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organic control body",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=255, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="common.Region",
                verbose_name="Region",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="residence_country_code",
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name="Residence country code"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="street",
            field=models.CharField(max_length=255, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="user",
            name="tax_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tax id"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="vat_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="VAT ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="website",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Website"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="zip",
            field=models.CharField(max_length=255, verbose_name="Zip code"),
        ),
    ]
