# Generated by Django 2.2.10 on 2020-07-28 08:54

import core.storage.utils
from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_auto_20200622_1345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycdocument",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to=core.storage.utils.private_image_upload_to,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="business_license",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to=core.storage.utils.private_image_upload_to,
                verbose_name="Business license",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.gcloud.GoogleCloudStorage(),
                upload_to=core.storage.utils.private_image_upload_to,
                verbose_name="ID photo",
            ),
        ),
    ]
