# Generated by Django 2.2.15 on 2020-10-29 08:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_auto_20200728_0854"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("Einzelunternehmer", "Einzelunternehmer"),
                    ("Landwirtschaftliche GbR", "Landwirtschaftliche GbR"),
                    ("Gewerbliche GbR", "Gewerbliche GbR"),
                    ("eG", "eG"),
                    ("KG", "KG"),
                    ("AG", "AG"),
                    ("GmbH", "GmbH"),
                    ("GmbH & Co. KG", "GmbH & Co. KG"),
                    ("UG (haftungsbeschränkt)", "UG (haftungsbeschränkt)"),
                    ("OHG", "OHG"),
                    ("Kollektivgesellschaft", "Kollektivgesellschaft"),
                    ("Kommanditgesellschaft", "Kommanditgesellschaft"),
                    ("e.V.", "e.V."),
                    ("Genossenschaft", "Genossenschaft"),
                    ("Verein", "Verein"),
                ],
                max_length=255,
                verbose_name="Company type",
            ),
        ),
    ]
