# Generated by Django 2.2.1 on 2019-11-05 14:32

import core.storage.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_auto_20191101_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.utils.public_image_upload_to),
        ),
    ]
