# Generated by Django 2.2.10 on 2020-05-20 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0003_auto_20191105_1432"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="container",
            options={"verbose_name": "Container", "verbose_name_plural": "Containers"},
        ),
        migrations.AlterField(
            model_name="container",
            name="delivery_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Container delivery fee cannot be negative"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="deposit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Container deposit cannot be negative"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="volume",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Container volume cannot be negative"
                    )
                ]
            ),
        ),
    ]
