# Generated by Django 2.2.10 on 2020-05-20 15:39

import core.storage.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0004_auto_20200520_1323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="delivery_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Container delivery fee cannot be negative"
                    )
                ],
                verbose_name="Delivery fee",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="deposit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Container deposit cannot be negative"
                    )
                ],
                verbose_name="Depoisit",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.storage.utils.public_image_upload_to,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="image_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Image url"
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="size_class",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Size class"
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="standard",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Standard container"
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="volume",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Container volume cannot be negative"
                    )
                ],
                verbose_name="Volume",
            ),
        ),
    ]
