# Generated by Django 2.2.15 on 2020-12-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200520_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='order_item',
        ),
    ]
