version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django
    versions:
    - ">= 3.a, < 4"
  - dependency-name: google-cloud-tasks
    versions:
    - ">= 2.a, < 3"
  - dependency-name: model-bakery
    versions:
    - 1.2.1
    - 1.3.0
  - dependency-name: google-cloud-storage
    versions:
    - 1.35.0
    - 1.35.1
    - 1.36.0
    - 1.36.1
    - 1.36.2
    - 1.37.0
  - dependency-name: google-cloud-logging
    versions:
    - 2.2.0
    - 2.3.0
  - dependency-name: django-tinymce
    versions:
    - 3.2.0
  - dependency-name: django-countries
    versions:
    - "7.0"
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
  - dependency-name: mangopaysdk
    versions:
    - 3.8.5
  - dependency-name: markdown
    versions:
    - 3.3.3
