runtime: python37
instance_class: F2

handlers:
    - url: /static
      static_dir: static/
    - url: /.*
      script: auto

inbound_services:
    - warmup

env_variables:
    SECRET_KEY: ""

    DEBUG: ""

    MAILGUN_API_KEY: ""
    MAILGUN_API_URL: ""
    MAILGUN_SENDER_DOMAIN: ""

    MANGOPAY_CLIENT_ID: ""
    MANGOPAY_PASSWORD: ""
    MANGOPAY_URL: ""

    HTML2PDF_BACKEND: ""

    SENTRY_DSN: ""

    DJANGO_ADMINS: ""
    REAL_ADMINS: ""

    DEFAULT_FROM_EMAIL: ""
    LOGISTICS_EMAIL: ""
    PLATFORM_EMAIL: ""
    INTERCOM_EMAIL: ""

    GOOGLE_CLOUD_PROJECT_LOCATION: ""
    DISTANCE_MATRIX_API_KEY: ""

    FEATURE_ROUTE: ""
    FEATURE_DELIVERY_DATE: ""

    POSTGRESQL_PASSWORD: ""
    POSTGRESQL_HOST: ""
    POSTGRESQL_USER: ""
    POSTGRESQL_PORT: ""
    POSTGRESQL_NAME: ""
