env_variables:
  DEBUG: ''
  DEFAULT_FROM_EMAIL: ''
  DISTANCE_MATRIX_API_KEY: ''
  DJANGO_ADMINS: ''
  FEATURE_DELIVERY_DATE: ''
  FEATURE_ROUTE: ''
  FEATURE_COMPANY_REGISTRATION_ID: ''
  GOOGLE_CLOUD_PROJECT_LOCATION: ''
  HTML2PDF_BACKEND: ''
  INTERCOM_EMAIL: ''
  LOGISTICS_EMAIL: ''
  MAILGUN_API_KEY: ''
  MAILGUN_API_URL: ''
  MAILGUN_SENDER_DOMAIN: ''
  MANGOPAY_CLIENT_ID: ''
  MANGOPAY_PASSWORD: ''
  MANGOPAY_URL: ''
  PLATFORM_EMAIL: ''
  POSTGRESQL_HOST: ''
  POSTGRESQL_NAME: ''
  POSTGRESQL_PASSWORD: ''
  POSTGRESQL_PORT: ''
  POSTGRESQL_USER: ''
  REAL_ADMINS: ''
  SECRET_KEY: ''
  SENTRY_DSN: ''
  STATIC_BUCKET: ''
  CURRENCY: ''

handlers:
- static_dir: static/
  url: /static
- script: auto
  secure: always
  url: /.*

inbound_services:
- warmup

instance_class: F2

runtime: python38

automatic_scaling:
    min_instances: 1
