import environ

env = environ.Env(DISTANCE_MATRIX_API_KEY=(str, ""))

GOOGLE_CLOUD_PROJECT = env("GOOGLE_CLOUD_PROJECT")
GOOGLE_CLOUD_PROJECT_LOCATION = env("GOOGLE_CLOUD_PROJECT_LOCATION")

GOOGLE_KEYS = {"DISTANCE_MATRIX_API_KEY": env("DISTANCE_MATRIX_API_KEY", "")}

DEFAULT_BUCKET = f"{GOOGLE_CLOUD_PROJECT}.appspot.com"
