# Generated by Django 2.2.4 on 2020-03-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_delivery_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='earliest_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
