# Generated by Django 2.2.4 on 2020-03-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("carts", "0003_cart_earliest_delivery_date")]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem", options={"ordering": ["created_at"]}
        )
    ]
