# Generated by Django 2.2.4 on 2020-03-30 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_addresses", "0002_auto_20200326_1208"),
        ("carts", "0005_auto_20200327_1800"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="delivery_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="delivery_addresses.DeliveryAddress",
            ),
        ),
    ]
