# Generated by Django 2.2.4 on 2020-02-05 06:44

from django.db import migrations, models


def add_region(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Region = apps.get_model('common', 'Region')
    Region.objects.using(db_alias).get_or_create(name="mcswiss")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(add_region, reverse_code=lambda *args: True)
    ]
