# Generated by Django 2.2.4 on 2020-04-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="region",
            name="website_slogan",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Slogan used in emails",
            ),
        )
    ]
