# Generated by Django 2.2.4 on 2020-04-10 11:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [("common", "0002_region_website_slogan")]

    operations = [
        migrations.AddField(
            model_name="region",
            name="mail_footer",
            field=tinymce.models.HTMLField(blank=True),
        )
    ]
