# Generated by Django 2.2.4 on 2020-04-10 16:19

import core.storage.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("common", "0003_region_mail_footer")]

    operations = [
        migrations.AddField(
            model_name="region",
            name="mail_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.storage.utils.public_image_upload_to,
            ),
        )
    ]
