# Generated by Django 2.2.10 on 2020-05-07 07:33

import core.storage.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_region_mail_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='mail_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.utils.public_logo_upload_to),
        ),
        migrations.AlterField(
            model_name='region',
            name='website_slogan',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Slogan used in emails'),
            preserve_default=False,
        ),
    ]
