# Generated by Django 2.2.10 on 2020-05-20 15:39

import core.storage.utils
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_auto_20200507_0733"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "Region", "verbose_name_plural": "Regions"},
        ),
        migrations.AlterField(
            model_name="region",
            name="mail_footer",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Mail footer"),
        ),
        migrations.AlterField(
            model_name="region",
            name="mail_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.storage.utils.public_logo_upload_to,
                verbose_name="Mail logo",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=32, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="region",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
    ]
