# Generated by Django 2.2.10 on 2020-05-22 13:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200520_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='contact',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='region',
            name='imprint',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Imprint'),
        ),
        migrations.AddField(
            model_name='region',
            name='prices',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Prices'),
        ),
        migrations.AddField(
            model_name='region',
            name='privacy_policy',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Privacy policy'),
        ),
        migrations.AddField(
            model_name='region',
            name='terms_of_services',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Terms of services'),
        ),
    ]
