# Generated by Django 2.2.10 on 2020-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_options", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryoption",
            options={
                "verbose_name": "Delivery option",
                "verbose_name_plural": "Delivery options",
            },
        ),
        migrations.AlterField(
            model_name="deliveryoption",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="deliveryoption",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="deliveryoption",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update at"),
        ),
    ]
