# Generated by Django 2.2.10 on 2020-06-22 13:47

from django.db import migrations, models
import overlays.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overlay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overlay_type', models.CharField(choices=[('anonymous', 'Anonymous user'), ('not_verified', 'Not verified user'), ('not_cooperative', 'Not cooperative user')], max_length=20, unique=True, verbose_name='Overlay type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('body', models.TextField(verbose_name='Body')),
                ('learn_more_url', models.CharField(blank=True, max_length=255, verbose_name='Learn more URL')),
                ('avatar', models.ImageField(upload_to=overlays.models.overlay_image_upload_to, verbose_name='Avatar')),
                ('image', models.ImageField(upload_to=overlays.models.overlay_image_upload_to, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
