# Generated by Django 2.2.10 on 2020-06-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overlays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overlay',
            options={'verbose_name': 'Overlay', 'verbose_name_plural': 'Overlays'},
        ),
        migrations.RemoveField(
            model_name='overlay',
            name='learn_more_url',
        ),
        migrations.AlterField(
            model_name='overlay',
            name='overlay_type',
            field=models.CharField(choices=[('anonymous', 'Anonymous user'), ('not_verified', 'Not verified user'), ('not_cooperative', 'Not cooperative user'), ('not_approved', 'Not approved user')], max_length=20, unique=True, verbose_name='Overlay type'),
        ),
        migrations.CreateModel(
            name='OverlayButton',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='overlays.Overlay', verbose_name='Overlay')),
            ],
            options={
                'verbose_name': 'Overlay button',
                'verbose_name_plural': 'Overlay buttons',
                'unique_together': {('overlay', 'order')},
            },
        ),
    ]
