# Generated by Django 2.2.10 on 2020-06-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overlays', '0002_auto_20200623_1210'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='overlaybutton',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='overlaybutton',
            name='overlay',
        ),
        migrations.DeleteModel(
            name='Overlay',
        ),
        migrations.DeleteModel(
            name='OverlayButton',
        ),
    ]
