# Generated by Django 2.2.10 on 2020-06-30 14:47

from django.db import migrations, models
import django.db.models.deletion
import overlays.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0007_auto_20200522_1329'),
        ('overlays', '0003_auto_20200630_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overlay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overlay_type', models.CharField(choices=[('anonymous', 'Anonymous user'), ('not_verified', 'Not verified user'), ('not_cooperative', 'Not cooperative user'), ('not_approved', 'Not approved user')], max_length=20, verbose_name='Overlay type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('body', models.TextField(verbose_name='Body')),
                ('avatar', models.ImageField(upload_to=overlays.models.overlay_image_upload_to, verbose_name='Avatar')),
                ('image', models.ImageField(upload_to=overlays.models.overlay_image_upload_to, verbose_name='Image')),
                ('region', models.ForeignKey(help_text='Region', on_delete=django.db.models.deletion.PROTECT, related_name='overlays', to='common.Region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Overlay',
                'verbose_name_plural': 'Overlays',
                'unique_together': {('overlay_type', 'region')},
            },
        ),
        migrations.CreateModel(
            name='OverlayButton',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='overlays.Overlay', verbose_name='Overlay')),
            ],
            options={
                'verbose_name': 'Overlay button',
                'verbose_name_plural': 'Overlay buttons',
                'unique_together': {('overlay', 'order')},
            },
        ),
    ]
