# Generated by Django 2.2.10 on 2020-07-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overlays', '0004_overlay_overlaybutton'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='overlaybutton',
            unique_together=set(),
        ),
    ]
