# Generated by Django 2.2rc1 on 2019-05-16 18:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import routes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(choices=[(1, routes.models.Days(1)), (2, routes.models.Days(2)), (3, routes.models.Days(3)), (4, routes.models.Days(4)), (5, routes.models.Days(5)), (6, routes.models.Days(6)), (7, routes.models.Days(7))]), size=7)),
                ('length', models.PositiveIntegerField(default=0)),
                ('routes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
