# Generated by Django 2.2rc1 on 2019-05-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='routes',
            new_name='waypoints',
        ),
    ]
