# Generated by Django 2.2rc1 on 2019-05-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20190517_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
