# Generated by Django 2.2rc1 on 2019-05-23 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20190517_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
