# Generated by Django 2.2.10 on 2020-05-07 07:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20190523_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='waypoints',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
