# Generated by Django 2.2.10 on 2020-05-07 07:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20200507_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='waypoints',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
