# Generated by Django 2.2.1 on 2019-07-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
