# Generated by Django 2.2.10 on 2020-05-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_item_valid_from"),
    ]

    operations = [
        migrations.AlterModelOptions(name="item", options={"verbose_name": "Items"},),
        migrations.AlterField(
            model_name="item", name="quantity", field=models.PositiveIntegerField(),
        ),
    ]
