# Generated by Django 2.2b1 on 2019-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mc_swiss_delivery_fee_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_insurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_purchase_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
