# Generated by Django 2.2.4 on 2020-02-06 09:11

from django.db import migrations, models
import django.db.models.deletion


def apply_region(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    RegionModel = apps.get_model("common", "Region")
    region, _ = RegionModel.objects.using(db_alias).get_or_create(name="mcswiss")

    SettingModel = apps.get_model('settings', 'Setting')
    SettingModel.objects.using(db_alias).update(region=region)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='common.Region'),
        ),
        migrations.RunPython(apply_region, reverse_code=lambda *args: True)
    ]
