# Generated by Django 2.2.4 on 2020-02-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_setting_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='common.Region'),
        ),
    ]
