# Generated by Django 2.2.4 on 2020-03-03 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0003_auto_20200206_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='central_logistics_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='logistics_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='setting',
            name='platform_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_setting', to=settings.AUTH_USER_MODEL),
        )
    ]
