# Generated by Django 2.2.4 on 2020-03-04 14:17
from django.conf import settings
from django.db import migrations


def fill_settings(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    UserModel = apps.get_model("users", "User")

    try:
        platform_user = UserModel.objects.using(db_alias).get(
            email=settings.PLATFORM_EMAIL
        )
    except UserModel.DoesNotExist:
        platform_user = None

    try:
        logistics_user = UserModel.objects.using(db_alias).get(
            email=settings.LOGISTICS_EMAIL
        )
    except UserModel.DoesNotExist:
        logistics_user = None

    SettingModel = apps.get_model("settings", "Setting")
    SettingModel.objects.using(db_alias).filter(region__slug="mcswiss").update(
        platform_user=platform_user, logistics_company=logistics_user
    )


def unfill_settings(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0004_auto_20200303_1336"),
    ]

    operations = [migrations.RunPython(fill_settings, reverse_code=unfill_settings)]
