# Generated by Django 2.2.4 on 2020-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("settings", "0005_auto_20200304_1417")]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="central_share",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Describes (in %) how much of platform fee should go to Traidoo Central. The rest will be transferred to regional platform user.",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="enable_platform_fee_share",
            field=models.BooleanField(
                default=False,
                help_text="Indicate if platform fee should be splitted between Traidoo Central and regional platform user",
            ),
        ),
    ]
