# Generated by Django 2.2.4 on 2020-03-24 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("settings", "0006_auto_20200311_1046")]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="central_share",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Describes (in %) how much of platform fee should go to Traidoo Central. The rest will be transferred to regional platform user.",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="enable_platform_fee_share",
            field=models.BooleanField(
                default=False,
                help_text="Indicate if platform fee should be split between Traidoo Central and regional platform user",
            ),
        ),
    ]
