# Generated by Django 2.2.4 on 2020-04-02 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20200324_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='central_share',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Describes (in %) how much of platform fee should go to Traidoo Central. The rest will be transferred to regional platform user.', max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0, message='Share should not be negative')]),
        ),
    ]
