# Generated by Django 2.2.10 on 2020-05-20 15:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0008_auto_20200402_1231"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="setting",
            options={"verbose_name": "Setting", "verbose_name_plural": "Settings"},
        ),
        migrations.AlterField(
            model_name="setting",
            name="central_logistics_company",
            field=models.BooleanField(
                default=True, verbose_name="Central logistic company available"
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="central_share",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Describes (in %) how much of platform fee should go to Traidoo Central. The rest will be transferred to regional platform user.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(
                        0, message="Share should not be negative"
                    ),
                ],
                verbose_name="Central platform share",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="charge",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Platform charge rate"
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="deposit_vat",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Deposit VAT rate"
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="enable_platform_fee_share",
            field=models.BooleanField(
                default=False,
                help_text="Indicate if platform fee should be split between Traidoo Central and regional platform user",
                verbose_name="Enable platform fee share",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="logistics_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Logistics company account",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="mc_swiss_delivery_fee_vat",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Central delivery fee VAT rate",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="min_purchase_value",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Min purchase value"
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="platform_fee_vat",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Platform fee VAT rate"
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="platform_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="region_setting",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Platform user account",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="settings",
                to="common.Region",
                verbose_name="Region",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="transport_insurance",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Transport insurance rate"
            ),
        ),
    ]
