# Generated by Django 2.2.13 on 2020-08-25 13:41

import django.core.validators
import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0009_auto_20200520_1539"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSetting",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_vat",
                    django_better_admin_arrayfield.models.fields.ArrayField(
                        base_field=models.DecimalField(
                            decimal_places=2,
                            max_digits=10,
                            validators=[
                                django.core.validators.MaxValueValidator(
                                    100, "VAT should not be more than 100%"
                                ),
                                django.core.validators.MinValueValidator(
                                    0, "VAT should not be negative"
                                ),
                            ],
                        ),
                        size=None,
                        verbose_name="Available product VAT rates",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global setting",
                "verbose_name_plural": "Global settings",
            },
        ),
    ]
