# Generated by Django 2.2rc1 on 2019-04-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='order',
            field=models.ForeignKey(default=123456789, on_delete=django.db.models.deletion.PROTECT, to='orders.Order'),
            preserve_default=False,
        ),
    ]
