# Generated by Django 2.2.4 on 2020-03-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("documents", "0002_auto_20190429_1606")]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("Platform Invoice", "documents/invoice_platform.html"),
                    ("Logistics Invoice", "documents/invoice_logistics.html"),
                    ("Producer Invoice", "documents/invoice_producer.html"),
                    (
                        "Order Confirmation Buyer",
                        "documents/order_confirmation_buyer.html",
                    ),
                    (
                        "Delivery Overview Buyer",
                        "documents/delivery_overview_buyer.html",
                    ),
                    (
                        "Delivery Overview Seller",
                        "documents/producer_delivery_note.html",
                    ),
                    ("Receipt Buyer", "documents/buyer_payment_receipt.html"),
                    ("Credit Note", "documents/credit_note.html"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="orders.Order",
            ),
        ),
    ]
