# Generated by Django 2.2.10 on 2020-05-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200410_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Buyer Platform Invoice', 'documents/invoice_platform.html'), ('Platform Invoice', 'documents/invoice_platform_producer.html'), ('Logistics Invoice', 'documents/invoice_logistics.html'), ('Producer Invoice', 'documents/invoice_producer.html'), ('Order Confirmation Buyer', 'documents/order_confirmation_buyer.html'), ('Delivery Overview Buyer', 'documents/delivery_overview_buyer.html'), ('Delivery Overview Seller', 'documents/producer_delivery_note.html'), ('Receipt Buyer', 'documents/buyer_payment_receipt.html'), ('Credit Note', 'documents/credit_note.html')], max_length=64),
        ),
    ]
