# Generated by Django 2.2.10 on 2020-05-20 15:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_auto_20200507_0733"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
        migrations.AlterField(
            model_name="document",
            name="bank_account_owner",
            field=models.CharField(
                blank=True,
                default="MANGOPAY SA",
                max_length=128,
                null=True,
                verbose_name="Bank account owner",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="blob_name",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Blob name in storage",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="buyer",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True, verbose_name="Buyer"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="delivery_address",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True, verbose_name="Delivery address"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("Buyer Platform Invoice", "documents/invoice_platform.html"),
                    ("Platform Invoice", "documents/invoice_platform_producer.html"),
                    ("Logistics Invoice", "documents/invoice_logistics.html"),
                    ("Producer Invoice", "documents/invoice_producer.html"),
                    (
                        "Order Confirmation Buyer",
                        "documents/order_confirmation_buyer.html",
                    ),
                    (
                        "Delivery Overview Buyer",
                        "documents/delivery_overview_buyer.html",
                    ),
                    (
                        "Delivery Overview Seller",
                        "documents/producer_delivery_note.html",
                    ),
                    ("Receipt Buyer", "documents/buyer_payment_receipt.html"),
                    ("Credit Note", "documents/credit_note.html"),
                ],
                max_length=64,
                verbose_name="Document type",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="lines",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True, verbose_name="Invoice lines"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="mangopay_payin_id",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Mangopay payin id"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="orders.Order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Is paid"),
        ),
        migrations.AlterField(
            model_name="document",
            name="payment_reference",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Payment reference"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="seller",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True, verbose_name="Seller"
            ),
        ),
    ]
