# Generated by Django 2.2.10 on 2020-07-10 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_auto_20200520_1539"),
        ("documents", "0006_auto_20200520_1539"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSendLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_send_logs",
                        to="orders.Order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
