# Generated by Django 2.2.10 on 2020-07-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_documentsendlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsendlog",
            name="sent",
            field=models.BooleanField(default=False),
        ),
    ]
