# Generated by Django 2.2.15 on 2020-11-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200520_1539'),
        ('documents', '0008_documentsendlog_sent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentsendlog',
            unique_together={('email', 'order')},
        ),
    ]
