# Generated by Django 2.2.10 on 2020-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_auto_20200520_1323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(max_length=255, verbose_name="Icon"),
        ),
        migrations.AlterField(
            model_name="category",
            name="ordering",
            field=models.IntegerField(blank=True, null=True, verbose_name="Ordering"),
        ),
    ]
