# Generated by Django 2.2.10 on 2020-08-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20200806_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.CategoryIcon', verbose_name='Icon'),
        ),
    ]
