# Generated by Django 2.2.10 on 2020-08-06 08:38

from django.db import migrations


def insert_icons(apps, schema_editor):
    Category = apps.get_model("categories", "Category")
    CategoryIcon = apps.get_model("categories", "CategoryIcon")

    for category in Category.objects.all():
        try:
            icon_id = int(category.icon)
        except ValueError:
            icon_id = 1

        category_icon = CategoryIcon.objects.get(id=icon_id)

        category.icon_link = category_icon
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0006_category_icon_link"),
    ]

    operations = [
        migrations.RunPython(insert_icons),
    ]
