# Generated by Django 2.2.10 on 2020-08-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20200806_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='categories.CategoryIcon', verbose_name='Icon'),
            preserve_default=False,
        ),
    ]
