# Generated by Django 2.2.10 on 2020-08-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_remove_category_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='icon_link',
            new_name='icon',
        ),
    ]
