# Generated by Django 2.2.4 on 2020-03-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryaddress',
            options={'ordering': ['id']},
        ),
    ]
