# Generated by Django 2.2.10 on 2020-05-20 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_addresses", "0002_auto_20200326_1208"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryaddress",
            options={
                "ordering": ["id"],
                "verbose_name": "Delivery address",
                "verbose_name_plural": "Delivery addresses",
            },
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="city",
            field=models.CharField(max_length=255, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="company_name",
            field=models.CharField(max_length=255, verbose_name="Company name"),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="street",
            field=models.CharField(max_length=255, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="zip",
            field=models.CharField(max_length=255, verbose_name="Zip code"),
        ),
    ]
