# Generated by Django 2.2b1 on 2019-03-19 07:31

from django.conf import settings as django_settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_options', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(django_settings.AUTH_USER_MODEL),
        ('delivery_addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'status',
                    models.IntegerField(
                        choices=[(0, 'Cart'), (1, 'Paid'), (2, 'Ordered')], default=0
                    ),
                ),
                ('total_price', models.FloatField(blank=True, null=True)),
                (
                    'payment_method',
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ('earliest_delivery_date', models.DateTimeField(blank=True, null=True)),
                (
                    'buyer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=django_settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'abstract': False},
            bases=(models.Model, ),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_delivery_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('product_snapshot', django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    'delivery_address',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='delivery_addresses.DeliveryAddress',
                    ),
                ),
                (
                    'delivery_option',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='delivery_options.DeliveryOption',
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='orders.Order',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='products.Product',
                    ),
                ),
            ],
            options={'unique_together': {('order', 'product', 'latest_delivery_date')}},
            bases=(models.Model, ),
        ),
    ]
