# Generated by Django 2.2.15 on 2020-12-18 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_remove_job_order_item"),
        ("orders", "0001_squashed_0008_auto_20200520_1539"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="jobs.Job",
                verbose_name="Job",
            ),
        ),
    ]
