# Generated by Django 2.2.1 on 2019-06-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0002_auto_20190429_1605")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
