# Generated by Django 2.2.1 on 2019-06-04 06:55

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    db_alias = schema_editor.connection.alias
    Order.objects.using(db_alias).update(processed=True)


class Migration(migrations.Migration):

    dependencies = [('orders', '0002_auto_20190429_1605')]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_func),
    ]
