# Generated by Django 2.2.1 on 2019-06-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0003_order_processed")]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
