# Generated by Django 2.2.4 on 2020-01-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
