# Generated by Django 2.2.4 on 2020-03-31 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
