# Generated by Django 2.2.10 on 2020-05-20 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_order_payment_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Buyer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="earliest_delivery_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Earliest delivery date"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="processed",
            field=models.BooleanField(default=False, verbose_name="Processed"),
        ),
        migrations.AlterField(
            model_name="order",
            name="region",
            field=models.ForeignKey(
                help_text="Region in which order took place",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="common.Region",
                verbose_name="Region",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Cart"), (1, "Paid"), (2, "Ordered")],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.FloatField(blank=True, null=True, verbose_name="Total price"),
        ),
    ]
