# Generated by Django 2.2rc1 on 2019-05-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('products', '0002_product_delivery_requirements')]

    operations = [
        migrations.AddField(
            model_name='product',
            name='third_party_delivery',
            field=models.BooleanField(default=False),
        )
    ]
