# Generated by Django 2.2.1 on 2019-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_third_party_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='container_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
