# Generated by Django 2.2.1 on 2019-07-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_container_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.CharField(blank=True, choices=[('weight', 'Weight (g) per item'), ('volume', 'Volume (l) per item')], max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
