# Generated by Django 2.2.1 on 2019-07-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190716_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='value',
            new_name='item_quantity',
        ),
    ]
