# Generated by Django 2.2.1 on 2019-09-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190718_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_gmo_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_grazing_animal',
            field=models.BooleanField(default=False),
        ),
    ]
