# Generated by Django 2.2.4 on 2020-02-05 06:44

from django.db import migrations, models
import django.db.models.deletion


def apply_region(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    RegionModel = apps.get_model("common", "Region")
    region, _ = RegionModel.objects.using(db_alias).get_or_create(name="mcswiss")

    ProductModel = apps.get_model('products', 'Product')
    ProductModel.objects.using(db_alias).update(region=region)


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('products', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Region of origin', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='common.Region'),
        ),
        migrations.AddField(
            model_name='product',
            name='regions',
            field=models.ManyToManyField(help_text='The associated regions the product should be available in', to='common.Region'),
        ),
        migrations.RunPython(apply_region, reverse_code=lambda *args: True)
    ]
