# Generated by Django 2.2.4 on 2020-02-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200205_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.ForeignKey(help_text='Region of origin', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='common.Region'),
        ),
    ]
