# Generated by Django 2.2.10 on 2020-05-20 13:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_auto_20200206_1358"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Amount should not be negative"
                    )
                ],
                verbose_name="Amount in lot",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="categories.Category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Delivery charge should not be negative"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_gluten_free",
            field=models.BooleanField(default=False, verbose_name="Is gluten free"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_gmo_free",
            field=models.BooleanField(default=False, verbose_name="Is gmo free"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_grazing_animal",
            field=models.BooleanField(default=False, verbose_name="Is grazing animal"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_organic",
            field=models.BooleanField(default=False, verbose_name="Is organic"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_vegan",
            field=models.BooleanField(default=False, verbose_name="Is vegan"),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Items quantity should not be negative"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Price should not be negative"
                    )
                ],
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="region",
            field=models.ForeignKey(
                help_text="Region of origin",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="common.Region",
                verbose_name="Region of origin",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="regions",
            field=models.ManyToManyField(
                help_text="The associated regions the product should be available in",
                to="common.Region",
                verbose_name="Available in regions",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Seller",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Unit"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="vat",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MaxValueValidator(
                        100, "VAT should not be more than 100%"
                    ),
                    django.core.validators.MinValueValidator(
                        0, message="VAT should not be negative"
                    ),
                ],
                verbose_name="VAT rate",
            ),
        ),
    ]
