# Generated by Django 2.2.10 on 2020-05-20 15:39

import core.storage.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_auto_20200520_1323"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Amount should not be negative"
                    )
                ],
                verbose_name="Amount in a lot",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="base_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weight", "Weight (g) per item"),
                    ("volume", "Volume (l) per item"),
                ],
                max_length=16,
                verbose_name="Base unit",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="container_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Container description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="container_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="containers.Container",
                verbose_name="Container type",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Delivery charge should not be negative"
                    )
                ],
                verbose_name="Delivery charge",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_options",
            field=models.ManyToManyField(
                to="delivery_options.DeliveryOption", verbose_name="Delivery options"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_requirements",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Delivery requirements",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.storage.utils.public_image_upload_to,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Image url"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_gmo_free",
            field=models.BooleanField(default=False, verbose_name="Is GMO free"),
        ),
        migrations.AlterField(
            model_name="product",
            name="item_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Items quantity should not be negative"
                    )
                ],
                verbose_name="Item quantity",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sellers_product_identifier",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Sellers product identifier",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="third_party_delivery",
            field=models.BooleanField(
                default=False, verbose_name="Third party delivery possible"
            ),
        ),
    ]
