# Generated by Django 2.2.10 on 2020-07-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_auto_20200622_1345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bigautofieldtaggeditem",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_bigautofieldtaggeditem_tagged_items",
                to="contenttypes.ContentType",
                verbose_name="Content type",
            ),
        ),
    ]
