# Generated by Django 2.2.15 on 2020-11-02 13:08

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200728_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigautofieldtaggeditem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_bigautofieldtaggeditem_tagged_items', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='products.BigAutoFieldTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
